#define wall 0
#define path 1
#define yellowkey 2
#define yellowdoor 3
#define bluekey 4
#define bluedoor 5
#define greenslime 6
#define redslime 7
#define littlebat 8
#define skelton 9
#define witch 10
#define ruby 11
#define sapphire 12
#define recoverypotion 13
#define smallrecoverypotion 14
#define skeltonsoilder 15
#define player 17
#define upstair 18
#define downstair 19
#define guard 20
#define trader 21
#define elder 22
#define begger 23
#define prisondoor 24
#define demonguard 25
#define demon 26
#define lava 100